Add two new useful modes to query for HDR support
MicrosoftDocs/win32 pull request #1666
Opened 2023-08-26 12:51 UTC by Filoppi

This page on HDR on Windows was great, but it was lackying information on some of the most common needs from developers.

The previously documented methods only allowed to query HDR support only if it was currently engaged.
This is very limiting for games that want to show an HDR/SDR toggle if HDR is supported but not engaged on the display.

A method to enable HDR from the an app has also been documented, given it's often requested by developers.

2023-08-26 13:20 UTC, Filoppi commented
> @Filoppi please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.

@microsoft-github-policy-service agree

2023-09-06 19:38 UTC, stevewhims commented
The purpose of CheckColorSpaceSupport isn't generally tied to HDR support of the monitor (which is perhaps what the changes in this PR imply). The product team is discussing what changes to make to the docs, so we won't be taking this PR at this time. I'll leave it open until we've updated the docs.

Thanks!
-Steve

2023-09-06 19:39 UTC, stevewhims requested changes
I'm just setting "Request changes" so that this isn't inadvertently merged. For more info, see the comment beginning "The purpose of CheckColorSpaceSupport isn't generally [...]".

2023-09-06 20:09 UTC, Filoppi commented
@stevewhims Using `CheckColorSpaceSupport()` to check for HDR10 (BT.2020) support is done in multiple Microsoft samples, hence why I added it to the page. If the bugs mentioned in the other PR (https://github.com/MicrosoftDocs/sdk-api/pull/1614) were fixed, it would then start to make more sense.

> See the comments in the thread.
I don't see any other comments if not the above ones mentioning the page is being reviewed.

2023-09-06 20:56 UTC, stevewhims commented
> @stevewhims Using `CheckColorSpaceSupport()` to check for HDR10 (BT.2020) support is done in multiple Microsoft samples, hence why I added it to the page. If the bugs mentioned in the other PR ([MicrosoftDocs/sdk-api#1614](https://github.com/MicrosoftDocs/sdk-api/pull/1614)) were fixed, it would then start to make more sense.
> 
> > See the comments in the thread.
> 
> I don't see any other comments if not the above ones mentioning the page is being reviewed.

Sorry, I've changed "see the comments" to "see the comment beginning "The purpose of CheckColorSpaceSupport isn't generally [...]"."

2026-07-17 17:12 UTC, GrantMeStrength approved these changes
LGTM — accurate improvement. Approved.

2026-07-17 20:26 UTC, GrantMeStrength commented
@copilot /review

2026-07-17 20:51 UTC, GrantMeStrength approved these changes
Reviewed ✅ — Documentation improvement looks good.

2026-07-18 11:21 UTC, closed without merging