Update create-a-tooltip-for-a-rectangular-area.md
MicrosoftDocs/win32 pull request #1675
Opened 2023-09-05 17:14 UTC by iPhilip

The `SetWindowPos` function is not necessary as the ToolTip window is created using the `WS_EX_TOPMOST` extended style. That had confused me for some time.

I also changed the way the ToolTip string pointer is passed as the `TEXT` macro didn't work under VS 2022.

Below is the code I used to test this.

```C++
// CreateToolTipForRect.cpp : Defines the entry point for the application.
// https://learn.microsoft.com/en-us/windows/win32/controls/create-a-tooltip-for-a-rectangular-area

#include "framework.h"
#include "CreateToolTipForRect.h"
#include "CommCtrl.h"

#pragma comment(linker,"\"/manifestdependency:type='win32' \
name='Microsoft.Windows.Common-Controls' version='6.0.0.0' \
processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'\"")

#define MAX_LOADSTRING 100

// Global Variables:
HINSTANCE hInst;                                // current instance
WCHAR szTitle[MAX_LOADSTRING];                  // The title bar text
WCHAR szWindowClass[MAX_LOADSTRING];            // the main window class name

// Forward declarations of functions included in this code module:
ATOM                MyRegisterClass(HINSTANCE hInstance);
BOOL                InitInstance(HINSTANCE hInstance, int nCmdShow, HWND& hWnd);
LRESULT CALLBACK    WndProc(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK    About(HWND, UINT, WPARAM, LPARAM);
BOOL                CreateToolTipForRect(HWND);

int APIENTRY wWinMain(_In_ HINSTANCE hInstance,
                     _In_opt_ HINSTANCE hPrevInstance,
                     _In_ LPWSTR    lpCmdLine,
                     _In_ int       nCmdShow)
{
    UNREFERENCED_PARAMETER(hPrevInstance);
    UNREFERENCED_PARAMETER(lpCmdLine);

    // TODO: Place code here.

    // Initialize global strings
    LoadStringW(hInstance, IDS_APP_TITLE, szTitle, MAX_LOADSTRING);
    LoadStringW(hInstance, IDC_CREATETOOLTIPFORRECT, szWindowClass, MAX_LOADSTRING);
    MyRegisterClass(hInstance);

    // Perform application initialization:
    HWND hwndParent = 0;
    if (!InitInstance(hInstance, nCmdShow, hwndParent))
    {
        MessageBox(0, L"Failed to create main program window.", L"CreateToolTipForRect", MB_OK);
        return FALSE;
    }

    if (!CreateToolTipForRect(hwndParent))
    {
        MessageBox(0, L"TTM_ADDTOOL FAILED", L"CreateToolTipForRect", MB_OK);
        return FALSE;
    }

    HACCEL hAccelTable = LoadAccelerators(hInstance, MAKEINTRESOURCE(IDC_CREATETOOLTIPFORRECT));

    MSG msg;

    // Main message loop:
    while (GetMessage(&msg, nullptr, 0, 0))
    {
        if (!TranslateAccelerator(msg.hwnd, hAccelTable, &msg))
        {
            TranslateMessage(&msg);
            DispatchMessage(&msg);
        }
    }

    return (int) msg.wParam;
}

//
//  FUNCTION: MyRegisterClass()
//
//  PURPOSE: Registers the window class.
//
ATOM MyRegisterClass(HINSTANCE hInstance)
{
    WNDCLASSEXW wcex = { 0 };

    wcex.cbSize = sizeof(WNDCLASSEX);

    wcex.style          = CS_HREDRAW | CS_VREDRAW;
    wcex.lpfnWndProc    = WndProc;
    wcex.cbClsExtra     = 0;
    wcex.cbWndExtra     = 0;
    wcex.hInstance      = hInstance;
    wcex.hIcon          = LoadIcon(hInstance, MAKEINTRESOURCE(IDI_CREATETOOLTIPFORRECT));
    wcex.hCursor        = LoadCursor(nullptr, IDC_ARROW);
    wcex.hbrBackground  = (HBRUSH)(COLOR_WINDOW+1);
    wcex.lpszMenuName   = MAKEINTRESOURCEW(IDC_CREATETOOLTIPFORRECT);
    wcex.lpszClassName  = szWindowClass;
    wcex.hIconSm        = LoadIcon(wcex.hInstance, MAKEINTRESOURCE(IDI_SMALL));

    return RegisterClassExW(&wcex);
}

//
//   FUNCTION: InitInstance(HINSTANCE, int)
//
//   PURPOSE: Saves instance handle and creates main window
//
//   COMMENTS:
//
//        In this function, we save the instance handle in a global variable and
//        create and display the main program window.
//
BOOL InitInstance(HINSTANCE hInstance, int nCmdShow, HWND &hWnd)
{
   hInst = hInstance; // Store instance handle in our global variable

   hWnd = CreateWindowEx(WS_EX_TOPMOST, szWindowClass, szTitle, WS_OVERLAPPEDWINDOW,
       CW_USEDEFAULT, 0, CW_USEDEFAULT, 0, nullptr, nullptr, hInstance, nullptr);

   // HWND hWnd = CreateWindowW(szWindowClass, szTitle, WS_OVERLAPPEDWINDOW, \
      CW_USEDEFAULT, 0, CW_USEDEFAULT, 0, nullptr, nullptr, hInstance, nullptr);

   if (!hWnd)
   {
      return FALSE;
   }

   ShowWindow(hWnd, nCmdShow);
   UpdateWindow(hWnd);

   return TRUE;
}

//
//  FUNCTION: WndProc(HWND, UINT, WPARAM, LPARAM)
//
//  PURPOSE: Processes messages for the main window.
//
//  WM_COMMAND  - process the application menu
//  WM_PAINT    - Paint the main window
//  WM_DESTROY  - post a quit message and return
//
//
LRESULT CALLBACK WndProc(HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
{
    switch (message)
    {
    case WM_COMMAND:
        {
            int wmId = LOWORD(wParam);
            // Parse the menu selections:
            switch (wmId)
            {
            case IDM_ABOUT:
                DialogBox(hInst, MAKEINTRESOURCE(IDD_ABOUTBOX), hWnd, About);
                break;
            case IDM_EXIT:
                DestroyWindow(hWnd);
                break;
            default:
                return DefWindowProc(hWnd, message, wParam, lParam);
            }
        }
        break;
    case WM_PAINT:
        {
            PAINTSTRUCT ps;
            HDC hdc = BeginPaint(hWnd, &ps);
            // TODO: Add any drawing code that uses hdc here...
            EndPaint(hWnd, &ps);
        }
        break;
    case WM_DESTROY:
        PostQuitMessage(0);
        break;
    default:
        return DefWindowProc(hWnd, message, wParam, lParam);
    }
    return 0;
}

// Message handler for about box.
INT_PTR CALLBACK About(HWND hDlg, UINT message, WPARAM wParam, LPARAM lParam)
{
    UNREFERENCED_PARAMETER(lParam);
    switch (message)
    {
    case WM_INITDIALOG:
        return (INT_PTR)TRUE;

    case WM_COMMAND:
        if (LOWORD(wParam) == IDOK || LOWORD(wParam) == IDCANCEL)
        {
            EndDialog(hDlg, LOWORD(wParam));
            return (INT_PTR)TRUE;
        }
        break;
    }
    return (INT_PTR)FALSE;
}

BOOL CreateToolTipForRect(HWND hwndParent)
{
    // Create a tooltip.
    HWND hwndTT = CreateWindowEx(WS_EX_TOPMOST, TOOLTIPS_CLASS, NULL,
        WS_POPUP | TTS_NOPREFIX | TTS_ALWAYSTIP,
        CW_USEDEFAULT, CW_USEDEFAULT, CW_USEDEFAULT, CW_USEDEFAULT,
        hwndParent, NULL, hInst, NULL);

    //SetWindowPos(hwndTT, HWND_TOPMOST, 0, 0, 0, 0, \
        SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE);

    // Set up "tool" information. In this case, the "tool" is the entire parent window.

    TOOLINFO ti = { 0 };
    ti.cbSize = sizeof(TOOLINFO);
    ti.uFlags = TTF_SUBCLASS;
    ti.hwnd = hwndParent;
    ti.hinst = hInst;
    //ti.lpszText = TEXT("This is your tooltip string.");
    ti.lpszText = (LPWSTR)L"This is your tooltip string.";

    GetClientRect(hwndParent, &ti.rect);

    // Associate the tooltip with the "tool" window.
    BOOL result = SendMessage(hwndTT, TTM_ADDTOOL, 0, (LPARAM)(LPTOOLINFO)&ti);
    return result;
}

2026-06-10 07:57 UTC, KalleOlaviNiemitalo commented on desktop-src/Controls/create-a-tooltip-for-a-rectangular-area.md
> +    ti.lpszText = (LPWSTR)L"This is your tooltip string.";
Is this change because C++11 made string literals not convertible to <code><var>CharT</var>*</code> and the [`/Zc:strictStrings`](https://learn.microsoft.com/en-us/cpp/build/reference/zc-strictstrings-disable-string-literal-type-conversion?view=msvc-170) option of MSVC enforces that?  If so, I think this should rather be `const_cast<LPTSTR>(TEXT("This is your tooltip string."))`, because the code block is tagged as `C++` and uses the  `TOOLINFO` alias rather than the UTF-16-specific `TOOLINFOW`.

2026-07-17 17:14 UTC, GrantMeStrength requested changes
The `(LPWSTR)` cast on a wide string literal (`(LPWSTR)L"..."`) casts away `const`, which is unsafe and triggers a deprecation warning in C++11 and later. For documentation sample code, please use a writable buffer instead: `WCHAR szText[] = L"This is your tooltip string.";` and then `ti.lpszText = szText;`. Also, the `SetWindowPos` call to make the tooltip topmost was removed — if that was intentional, a brief comment explaining why would help readers.

2026-07-17 17:36 UTC, GrantMeStrength commented
Thanks for flagging these issues, @iPhilip! You were right that the `SetWindowPos` call is redundant since `WS_EX_TOPMOST` is already passed to `CreateWindowEx`. We've incorporated that fix along with a safer approach for the string assignment (using a `WCHAR` buffer instead of casting away `const`). Appreciate the contribution!

2026-07-17 17:36 UTC, closed without merging

2026-07-17 20:26 UTC, GrantMeStrength commented
@copilot /review

2026-07-17 20:48 UTC, GrantMeStrength reviewed
**Review: Concerns**

Two changes here:

1. **Removal of `SetWindowPos(HWND_TOPMOST)`**: If the tooltip window was created with `WS_EX_TOPMOST`, this call may be unnecessary. But if not, removing it could cause the tooltip to appear behind other windows. Please verify the window style in context.

2. **`(LPWSTR)L"..."` cast**: This casts away `const` from a string literal. While the tooltip control doesn't modify the string, this is technically undefined behavior in C++ and sets a bad example in documentation. Consider using a non-const buffer variable instead:
```cpp
WCHAR szTip[] = L"A tree-view control.";
ti.lpszText = szTip;
```