Update win-dialog-box.md
MicrosoftDocs/win32 pull request #210
Opened 2020-02-10 06:41 UTC by RussKie

2020-02-10 06:41 UTC, PRMerger16 commented
@RussKie : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-02-11 21:45 UTC, hickeys commented
@RussKie Just one quick change and this is ready to go

2020-02-12 18:43 UTC, hickeys requested changes

2020-02-12 18:43 UTC, hickeys commented on desktop-src/uxguide/win-dialog-box.md
> +**Consider using icons to help users visually recognize your program's features.** This technique is most effective when the icons are easily recognizable and used in several locations within your pr
Based on the formatting of other examples on this page, **"Consider using icons to help..."** needs to be a bullet point beneath "In this example..." Otherwise this looks perfect. Thanks for catching this.

2020-02-13 00:43 UTC, RussKie commented on desktop-src/uxguide/win-dialog-box.md
> +**Consider using icons to help users visually recognize your program's features.** This technique is most effective when the icons are easily recognizable and used in several locations within your pr
Fixed

2020-02-14 20:59 UTC, hickeys approved these changes
Perfect. Thanks for making this tweak.

2020-02-14 20:59 UTC, hickeys commented
#sign-off

2020-02-14 22:05 UTC, merged