Update prog-dx-with-com.md
MicrosoftDocs/win32 pull request #502
Opened 2020-09-02 19:07 UTC by walbourn

Added more information about smart-pointer choices, link libraries, and the IID_PPV_ARGS macro

2020-09-02 19:08 UTC, PRMerger7 commented
@walbourn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-09-03 19:39 UTC, cremno requested changes

2020-09-03 19:39 UTC, cremno commented on desktop-src/prog-dx-with-com.md
> +> DirectX applications should link with ``dxguid.lib`` and ``uuid.lib`` to provide definitions for the varoius interface and class GUIDs. Visual C++ and other compilers support the **__uuidof** opera
>explicilt

typo

2020-09-03 19:39 UTC, cremno commented on desktop-src/prog-dx-with-com.md
> +> In C++ you can make use of the ``IID_PPV_ARGS`` macro rather thant the explicit IID and cast pointer: ``pDXGISwapChain1->QueryInterface(IID_PPV_ARGS(&pDXGISwapChain3));``.
>thant

2020-09-03 20:12 UTC, PRMerger8 commented
@walbourn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-09-04 21:53 UTC, stevewhims approved these changes

2020-09-04 21:54 UTC, merged