Added steps for signing with Azure Code Sign to ELAM driver resource …
MicrosoftDocs/win32 pull request #730
Opened 2021-02-05 19:51 UTC by jgeurten

…file info. Need to wait for the PCA cert to be included in pkiops

2021-02-05 19:52 UTC, PRMerger19 commented
@jgeurten : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-02-05 20:06 UTC, PRMerger7 commented
@mcleanbyron : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-02-05 22:35 UTC, PRMerger15 commented
@jgeurten : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-11-24 18:26 UTC, GrantMeStrength commented
Authoring waiting for more information.

2024-01-12 18:11 UTC, GrantMeStrength requested changes
I am sorry this PR was not approved when it was submitted.
Is it still accurate?

2024-01-12 19:00 UTC, jgeurten commented
@GrantMeStrength it is still accurate/required to be documented. The product "Azure Code Sign" has been rebranded to "Trusted Signing"

2024-01-24 22:47 UTC, GrantMeStrength approved these changes

2024-01-24 22:53 UTC, GrantMeStrength commented
Updated references to "Azure Code Sign"  to "Trusted Signing"

2026-01-13 18:28 UTC, GrantMeStrength commented
Is this PR ready to go live?

2026-07-14 20:12 UTC, GrantMeStrength commented
Closing this pull request because it has been open for more than three years. If the change is still relevant, please open a new pull request against the current branch.

2026-07-14 20:12 UTC, closed without merging