Update text-ui.md
MicrosoftDocs/win32 pull request #971
Opened 2021-08-19 01:27 UTC by pallabiwrites

Fixed minor changes.

2021-08-19 01:28 UTC, PRMerger7 commented
@pallabiwrites : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-11-17 19:02 UTC, hickeys requested changes, later dismissed

2021-11-17 19:02 UTC, hickeys commented on desktop-src/uxguide/text-ui.md
> +Redundant text not only takes valuable screen space, but weakens the effectiveness of the important ideas or actions that you are trying to convey. It is also a waste of the reader's time, and all th
Here, Windows is a singular proper noun, and 'strives' is correct. Please revert this change.

2021-11-17 19:02 UTC, hickeys commented on desktop-src/uxguide/text-ui.md
> +Review each window and eliminate duplicate words and statements, both within and across controls. Don't avoid important text; be explicit wherever necessary, but don't be redundant and don't explain
I 💖 ;

2022-10-18 19:04 UTC, Karl-Bridge-Microsoft approved these changes

2022-10-18 19:05 UTC, merged